### ISSUE TITLE
run_cfg_file

### ISSUE THREAD

**Issue by Cao-Cong0** [liren2515/DrapeNet#10]
When I run the export_codes.py, I need to input the run_cfg_file, what should the run_cfg_file be? Thank you!

**Comment by liren2515** [comment]
It should be [this file](https://github.com/liren2515/DrapeNet/blob/main/cfg/encdec.yaml).

**Comment by Cao-Cong0** [comment]
> It should be [this file](https://github.com/liren2515/DrapeNet/blob/main/cfg/encdec.yaml).

But I got the error:

python3 export_codes.py /home/cong/DrapeNet/cfg/encdec.yaml
Traceback (most recent call last):
  File "export_codes.py", line 73, in <module>
    main()
  File "/home/cong/anaconda3/envs/DrapeNet/lib/python3.8/site-packages/hesiod/core.py", line 227, in decorated_fn
    return fn(*args, **kwargs)
  File "export_codes.py", line 27, in main
    ckpt_path = list((get_out_dir() / "ckpts").glob("last*.pt"))[0]
IndexError: list index out of range

**Comment by liren2515** [comment]
`ckpt_path` should be the path to your checkpoint. Maybe you can check if it points to the right directory.

**Comment by Cao-Cong0** [comment]
Now I get it, the run_cfg_file for export_codes.py is the run.yaml of train_encdec.py. 

Another question is, in the checkpoints you provided, we have bottom_codes.pt, bottom_udf.pt, top_codes.pt, top_udf.pt, I am wondering how to get those. 
Are they the latent codes that can be obtained after running the export_codes.py?  Then what about the udf.pt and those .pth files?

Really appreciate your help!

**Comment by liren2515** [comment]
`bottom_udf.pt` and `top_udf.pt` are the checkpoints of udf models for the bottom/top garments. `bottom_udf.pt` and `top_udf.pt` are the latent codes. You can get the latent codes by running `export_codes.py`.

**Comment by Cao-Cong0** [comment]
Thank you so so so much! You helps a lot!
