### ISSUE TITLE
How to generate the lbs.pth file

### ISSUE THREAD

**Issue by Cao-Cong0** [liren2515/DrapeNet#11]
In the checkpoints you provided there are lbs.pth, lbs_shape.pth, lbs_deform_top.pth, lbs_deform_layer.pth, lbs_deform_bottom.pth, I am wondering which part generates them? How can I get them from training?

**Comment by Cao-Cong0** [comment]
And I am also wondering how can I apply different poses. How to get more new pose-sample.pt?

**Comment by liren2515** [comment]
> In the checkpoints you provided there are lbs.pth, lbs_shape.pth, lbs_deform_top.pth, lbs_deform_layer.pth, lbs_deform_bottom.pth, I am wondering which part generates them? How can I get them from training?

We don't provide the codes for the training of `lbs*.pth`. You can find the training details in our paper.

> And I am also wondering how can I apply different poses. How to get more new pose-sample.pt?

To get more pose samples, you can use sequences from AMASS dataset, following the instruction from [here](https://github.com/isantesteban/snug).
