### ISSUE TITLE
Pre-process my own dataset from Clothes3D dataset

### ISSUE THREAD

**Issue by boqian-li** [liren2515/DrapeNet#14]
Hi, I want to make my own dataset in which we need clothes on different smpl shapes and include skirts. 
Could you please tell me how to preprocess the Clothes3D dataset to the version you use in DrapeNet? Just like fit the clothes on a specific SMPL model.

**Comment by iris112358** [comment]
Is here any update on this? Thanks!

**Comment by liren2515** [comment]
There are many ways to do it. The simplest way is to query the closest body vertex for each garment vertex, and then move it according to the displacement of the body vertex. You need post processing like smoothing to make the garment look better.

**Comment by sunshineatnoon** [comment]
Thanks! @liren2515 I have another question, does the autoencoder includes dresses?

**Comment by liren2515** [comment]
> Thanks! @liren2515 I have another question, does the autoencoder includes dresses?

No, in this work, we didn't train a model for the dress.

**Comment by sunshineatnoon** [comment]
> > Thanks! @liren2515 I have another question, does the autoencoder includes dresses?
> 
> No, in this work, we didn't train a model for the dress.

Thanks so much! @liren2515 If I train the auto-encoder on a dress dataset, is there anything I need to specifically pay attention to?

**Comment by liren2515** [comment]
> > > Thanks! @liren2515 I have another question, does the autoencoder includes dresses?
> > 
> > 
> > No, in this work, we didn't train a model for the dress.
> 
> Thanks so much! @liren2515 If I train the auto-encoder on a dress dataset, is there anything I need to specifically pay attention to?

I think you only need to normalize your data to [0,1] and follow `encdec/preprocess_udf.py` to prepare your data.

**Comment by boqian-li** [comment]
> There are many ways to do it. The simplest way is to query the closest body vertex for each garment vertex, and then move it according to the displacement of the body vertex. You need post processing like smoothing to make the garment look better.

Thanks. I have another question: What should be done if the scales and relative positions of the cloth-mesh and smpl-mesh are mismatched. How can I adjust the relative positions and the scale automatically?

**Comment by liren2515** [comment]
> > There are many ways to do it. The simplest way is to query the closest body vertex for each garment vertex, and then move it according to the displacement of the body vertex. You need post processing like smoothing to make the garment look better.
> 
> Thanks. I have another question: What should be done if the scales and relative positions of the cloth-mesh and smpl-mesh are mismatched. How can I adjust the relative positions and the scale automatically?

Sorry, I don't have a general answer for it. It's better you have the cloth is draped on a body. Then you can do something. Otherwise, I think you need some hacks there.

**Comment by boqian-li** [comment]
Hi, thanks for your advice. I have another question:
I want to encode a mesh with more pleats like a skirt or more details on it compared with a simple top. But with the default network structure and all other configurations, the reconstruction result is not good. The main symptoms are: holes appear or part of the mesh is separated from the main part. Do you have any suggestions in this regard, such as adjusting any configuration or network structure, etc. Thanks.

**Comment by liren2515** [comment]
Did you try to overfit on a single skirt mesh? Actually, learning an accurate 0-isosurface is a bit hard. The gradient around it is a bit noisy. If you don't get a good overfitting on a single mesh, that means you may need to consider a new model for UDF. I remember there are some papers that focus on improving the reconstruction quality of UDF. You may need to check them.

**Comment by boqian-li** [comment]
> Did you try to overfit on a single skirt mesh? Actually, learning an accurate 0-isosurface is a bit hard. The gradient around it is a bit noisy. If you don't get a good overfitting on a single mesh, that means you may need to consider a new model for UDF. I remember there are some papers that focus on improving the reconstruction quality of UDF. You may need to check them.

Thanks, that's a good insight and I will have a try. 

Aside from that, could you please provide some insights on the following questions：
1. Why there are staircase artifact on some of the reconstructed meshes: 
![image](https://github.com/liren2515/DrapeNet/assets/88582462/728eb8ab-ef16-449d-b5bc-3b8718ca5145)

2. Why when I test the model on meshes which are not included in thr train-dataset, there are some holes on the reconstructed meshes, like this: 
![image](https://github.com/liren2515/DrapeNet/assets/88582462/237ab41e-793d-40d0-9707-93c9f0ef92a6)
![image](https://github.com/liren2515/DrapeNet/assets/88582462/5caf7182-0a59-4e0b-80a2-583547790572)

**Comment by liren2515** [comment]
For the first question, increasing the resolution may help. If not, then it is related to 'Learning an accurate 0-isosurface is a bit hard. The gradient around it is a bit noisy.' 

For the second one, how do you get that mesh? By passing it to the encoder to get the latent code, or by optimizing  the latent code to make the decoder reconstruct the given mesh?

**Comment by boqian-li** [comment]
> For the first question, increasing the resolution may help. If not, then it is related to 'Learning an accurate 0-isosurface is a bit hard. The gradient around it is a bit noisy.'
> 
> For the second one, how do you get that mesh? By passing it to the encoder to get the latent code, or by optimizing the latent code to make the decoder reconstruct the given mesh?

Hi, thanks for your reply. 
Yes, I trained the encoder and decoder on the meshes and passed the point cloud to the encoder and reconstruct from decoder. I want to add that I have many meshes in my dataset. So for the purpose of quick training, I increased the lr and reduced the number of epoch.

**Comment by liren2515** [comment]
If your test mesh is quite different from the training ones, the holes can happen I think.

**Comment by boqian-li** [comment]
Thanks, I will pay more attention to that point. 
I wanna know why the DGCNN net you implemented is different from the original version? for example, you replaced the Conv2D with the linear. Are there any insights on that?

**Comment by liren2515** [comment]
> Thanks, I will pay more attention to that point. I wanna know why the DGCNN net you implemented is different from the original version? for example, you replaced the Conv2D with the linear. Are there any insights on that?

The Conv2D in DGCNN has a kernel of size 1. It is equivalent to a linear layer.

**Comment by sunshineatnoon** [comment]
Hi @liren2515 I have a related question about training the auto-encoder. The total epoch is 4000, which takes about few days on a V100. Is that expected?
