### ISSUE TITLE
Incomplete reconstructed mesh

### ISSUE THREAD

**Issue by Cao-Cong0** [liren2515/DrapeNet#15]
Hello! Now I am trying to get the latent code for my own data. The cloth I am using is not around the original point, it's above.
![image](https://github.com/liren2515/DrapeNet/assets/73863996/2d0fff24-b701-4e07-9fa1-64222aa19a7e)
I use your checkpoint to generate the code and reconstruct from the code. The reconstrructed mesh is incomplete.

So I adjust the cloth3d dataset by moving all of them along the z axis in a distance with the range from 0.8 to 0.4. And then train the encdec with this dataset. All the parameters are the same as yours. Now it has trained 3200 epochs. But the reconstructed mesh is still incomplete. 
![image](https://github.com/liren2515/DrapeNet/assets/73863996/754d749b-1283-4534-9521-ab272cf69d62)
Do you have any idea to solve this issue?

**Comment by liren2515** [comment]
why not align your mesh to the range of cloth3d, which is in [0, 1]?

**Comment by boqian-li** [comment]
@Cao-Cong0 Hi, I wanna know how did you reconstruct such a complex surface? I mean there are lots of wrinkles on the surface which make it difficult to reconstruct perfectly.

**Comment by Cao-Cong0** [comment]
> @Cao-Cong0 Hi, I wanna know how did you reconstruct such a complex surface? I mean there are lots of wrinkles on the surface which make it difficult to reconstruct perfectly.

I didn't continue to reconstruct this mesh. But previously I did experiments on other complex mesh, such as multi-layer mesh, it's true that perfect reconstruction is hard to realize.
