### ISSUE TITLE
Constraint on latent code for 3D/image fitting

### ISSUE THREAD

**Issue by sunshineatnoon** [liren2515/DrapeNet#16]
Hi @liren2515 Thanks for open-sourcing this awesome work. I have a question about fitting a 3D garment mesh or an image using DrapeNet. As far as I understand, this is done by freezing the decoder and optimizing a latent code. However, what if the latent code goes out of distribution the latent space ? For example, in the images below, the optimized mesh has some floaters:
![Picture1](https://github.com/liren2515/DrapeNet/assets/7546747/100cb144-8528-4000-89e6-46c2b38c51e0)

**Comment by boqian-li** [comment]
Hi, I wanna know have u solved this problem?

**Comment by dahuerfanov** [comment]
Hi, does anybody have any thoughts on this? Thanks!
