### ISSUE TITLE
Question about auto-encoder architecture

### ISSUE THREAD

**Issue by sunshineatnoon** [liren2515/DrapeNet#17]
Hi, Thanks for open-sourcing the repo. I have a question about the auto-encoder structure. I am wondering have you tried to learn a VAE instead of AE? This way the latent space might be more smooth.

**Comment by liren2515** [comment]
Thanks for your interest.

Actually, we didn't experiment with VAE. This is an interesting point and worth trying.

**Comment by sunshineatnoon** [comment]
Thanks for the answer!
