### ISSUE TITLE
Canonical SMPL Pose Parameter

### ISSUE THREAD

**Issue by sunshineatnoon** [liren2515/DrapeNet#18]
Hi, I have a question about the default body pose aligned with the garments from CLOTH3D. As shown below, the rest pose body from `smpl_server` seems to be misaligned with the pants. Did you use a specific rest pose to produce the canonical garment meshes?

![snapshot00](https://github.com/liren2515/DrapeNet/assets/7546747/fc982087-53f4-42f2-b08e-ed922c23654b)

**Comment by liren2515** [comment]
We use the rest pose of CLOTH3D, which is defined as:
```
pose = pose.reshape(1, 24, 3)
pose[0, 1, 2] = 0.15
pose[0, 2, 2] = -0.15
pose = pose.reshape(1, 72)
```

**Comment by sunshineatnoon** [comment]
Thanks for the reply!
