### ISSUE TITLE
Pre-trained weights of the models

### ISSUE THREAD

**Issue by NagabhushanSN24** [liren2515/DrapeNet#21]
Hi,

Would it be possible to share the pretrained weights of your model?

Thanks

**Comment by liren2515** [comment]
Hello,

All the pretrained models are included in the [repo](https://github.com/liren2515/DrapeNet/tree/main/checkpoints).

**Comment by NagabhushanSN24** [comment]
Sorry, my bad. Thanks for the quick reply
