### ISSUE TITLE
export_meshes.py - Issue with get_mesh_from_udf()

### ISSUE THREAD

**Issue by ImaneChafi** [liren2515/DrapeNet#3]
Hi, 

Thank you for this great code! I was wondering if your team had more information about how to run the `export_meshes.py` code. A few issues arise from the `get_mesh_from_udf()` function. For example, the function breaks on a high number of `max_batch`. Sometimes there is also a CUDA error on memory allocation using this function. Would you perhaps have a documentation on how the `get_mesh_from_udf()` parameters in `export_meshes.py` were chosen? 

Thank you and have a good day!
Imane

**Comment by liren2515** [comment]
We are running our models on V100 with 32G memory. A large number for `max_batch` or mesh resolution will raise `out of memory` error when you have a GPU with small memory.

**Comment by ImaneChafi** [comment]
Thank you for your answer!
