### ISSUE TITLE
Is there a way to control the compression factor of the clothes? Does this work support that?

### ISSUE THREAD

**Issue by iyyovvv** [liren2515/DrapeNet#7]

**Comment by liren2515** [comment]
Hello, what do you mean by 'the compression factor'?

**Comment by iyyovvv** [comment]
@liren2515 By 'the compression factor', I mean if clothes can stretch? For example, the stretchability of a sweater is better than that of a leather jacket. Therefore the deformation will be different.

**Comment by liren2515** [comment]
We didn't consider the controlling of the garment material parameters. Our deformation model is trained with fixed material parameters from [SNUG](https://github.com/isantesteban/snug). But it should be able to be extended to support that, such as making the material parameters as the input of the draping model.

**Comment by iyyovvv** [comment]
@liren2515 thank you.
